# Homework Assignment 7 - Evan Callaghan & Bryce Dean

### 1. Considering the histogram of salary (in thousands) of MLB players in 1987 season 

### a) Describe the 1987 MLB season salary distribution
#### The 1987 MLB season salary dsitribution is right skewed with a peak at around 200,000 dollars.

### b) A data scientist proposes using the log-transformation on the salary variable. The resulting variable is likely to be:
#### i. Less skewed

### 2. Which of the following is the best way to determine whether or not there is statistically significant linear relationship between two numeric variables?
#### C. Compare the estimated slope and its margin of error

### 3. What is the difference between simple linear regression and multiple linear regression?

#### Simple linear regression relates a response variable, Y, to a single predictor variable, X. On the other hand, multiple linear regression relates a response variable, Y, to multiple predictor variables, X1, X2, ..., Xn.

### 4. In multiple linear regression, the least squares regression line minimizes the sum of the:

#### D. Squared differences between actual and predicted Y values

In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

## 5. a) Using pandas to read the csv file and create a data-frame called hitters and remove observations with missing values

hitters = pd.read_csv('Hitters.csv')
hitters.head()

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
0,293,66,1,30,29,14,1,293,66,1,30,29,14,A,E,446,33,20,NaN,A
1,315,81,7,24,38,39,14,3449,835,69,321,414,375,N,W,632,43,10,475.0,N
2,479,130,18,66,72,76,3,1624,457,63,224,266,263,A,W,880,82,14,480.0,A
3,496,141,20,65,78,37,11,5628,1575,225,828,838,354,N,E,200,11,3,500.0,N
4,321,87,10,39,42,30,2,396,101,12,48,46,33,N,E,805,40,4,91.5,N

In [2]:
## b) Creating two new variables:
## log_Salary that represents the log of Salary
## League_0_1 that takes the value of 1 when League = A and 0 otherwise

hitters['log_Salary'] = np.log(hitters['Salary'])
hitters['League_0_1'] = np.where(hitters['League'] == 'A', 1, 0)

In [3]:
## c) Building a linear regression model in which AtBat, Hits, HmRun, and League_0_1 are the predictor 
## variables and log_Salary is the target variable

## Building the model
mlr_md = smf.ols(formula = 'log_Salary ~ AtBat + Hits + HmRun + League_0_1', data = hitters).fit()

## i) Reporting the coefficient of determination
mlr_md.summary()

## The coefficient of determination (R-squared value) for the given model is 0.233. In terms of this probelm, 
## a coefficient of determination equal to 0.233 means that about 23% of the variability in Y (log_Salary) can 
## be explained by a linear model in which AtBat, Hits, HmRun, and League_0_1 are the predictor variables.

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             log_Salary   R-squared:                       0.233
Model:                            OLS   Adj. R-squared:                  0.221
Method:                 Least Squares   F-statistic:                     19.56
Date:                Wed, 03 Nov 2021   Prob (F-statistic):           4.51e-14
Time:                        16:44:10   Log-Likelihood:                -306.97
No. Observations:                 263   AIC:                             623.9
Df Residuals:                     258   BIC:                             641.8
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.1585      0.153     33.671      0.000       4.857       5.460
AtBat         -0.0022      0.001     -1.748      0.082      -0.005       0.000
Hits           0.0142      0.004      3.508      0.001       0.006       0.022
HmRun          0.0183      0.007      2.714      0.007       0.005       0.032
League_0_1    -0.1570      0.100     -1.577      0.116      -0.353       0.039
==============================================================================
Omnibus:                        4.364   Durbin-Watson:                   1.880
Prob(Omnibus):                  0.113   Jarque-Bera (JB):                3.997
Skew:                          -0.236   Prob(JB):                        0.136
Kurtosis:                       2.622   Cond. No.                     1.43e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.43e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
## ii) Describing the relationship between log_Salary and AtBat

## log_Salary and AtBat have a slightly negative relationship. The coefficient associated with AtBats is -0.0022 
## with a standard error of 0.001. Since the magnitude of the coefficient is larger than two times the magnitude
## of the standard error, we know that the relationship between log_Salary and AtBat is significant.

In [ ]:
## iii) Describing the relationship between log_Salary and League_0_1

## The coefficient associated with League_0_1 is -0.1570 with a standard error of 0.1. Since two times the magnitude 
## of the standard error is greater than the magnitude of the coefficient, we know that the relationship between 
## log_Salary and League_0_1 is not statistically significant.

In [4]:
## iv) Predicting the salary of a baseball player in the 1987 season with AtBat = 600, Hits = 220, 
## HmRun = 35 and League_0_1 = 0

## Building the new data frame
data = pd.DataFrame({'AtBat': [600], 'Hits': [220], 'HmRun': [35], 'League_0_1': [0]})

## Predicting on the new data
pred = mlr_md.predict(data)

## Transforming the log prediction into the actual predicted salary
np.exp(pred)

## The estimated salary for a player with AtBat = 600, Hits = 220, HmRun = 35 and League_0_1 = 0
## is approximately $1,990,548.

0    1990.547653
dtype: float64

In [5]:
## v) Predicting the salary of a baseball player in the 1987 season with AtBat = 600, Hits = 220,
## HmRun = 35 and League_0_1 = 1.

## Building the new data frame
data = pd.DataFrame({'AtBat': [600], 'Hits': [220], 'HmRun': [35], 'League_0_1': [1]})

## Predicting on the new data
pred = mlr_md.predict(data)

## Transforming the log prediction into the actual predicted salary
np.exp(pred)

## The estimated salary for a player with AtBat = 600, Hits = 220, HmRun = 35 and League_0_1 = 1
## is approximately $1,701,308.

0    1701.307793
dtype: float64

In [ ]:
## vi) We can conclude that players with similar statistics make a higher salary in the National League (league_0_1 = 0)
## compared to players in the American League (league_0_1 = 1).