# Sports Analytics Exam 2 - Evan Callaghan

### 1. True or False
#### a) The correlation coefficient is affect by outliers. TRUE
#### b) In simple linear regression models, the coefficient of determination can be computed as the square of the correlation coefficient. TRUE
#### c) In linear regression models, larger residuals are preferred. FALSE
#### d) In linear regression models, variables that are not statistically significant can be removed from the model. TRUE
#### e) The larger the margin of error the more likely the variable is statistically significant. FALSE
#### f) A correlation coefficient equal to 0.45 with a margin of error equal to 0.53 implies that the correlation coefficient is not statistically significant. TRUE
#### g) As the number of variables in a linear model increase, the coefficient of determination of the model increases as well. TRUE
#### h) Linear models are not affected by outliers. FALSE
#### i) Linear models are affected by outliers. TRUE
#### j) The coefficient of determination is a number between -1 and 1. FALSE

### 2. Which of the following is/are NOT TRUE about the correlation coefficient?

#### B and C are not true. The correlation coefficient is affected by outliers and it is not affected by the scale.

### 3. Considering the following linear model: Y = β0 + β1X1 + β2X2. What does β1 imply?

#### β1 represents the estimated coefficient associated to the X1 input variable. β1 implies that while holding everything else constant, for an increase of one unit in X1, the target variable, Y, will increase by an amount of β1, on average.

### 4. Nadal’s performance on clay to his performance on other surfaces during the period 2008-2012 is shown in the below table.

### a) Compute the correlation coefficient.
#### a = 3658, b = 2715, c = 1660, d = 863
#### r = (ad - bc) / sqrt((a + b)(c + d)(a + c)(b + d))
#### r = (3658 * 863 - 2715 * 1660) / sqrt((3658 + 2715)(1660 + 863)(3658 + 1660)(2715 + 863))
#### r = -0.077

#### n = 8896
#### ME = 2 * sqrt((1 - r^2) / n)
#### ME = 2 * sqrt(1 - (-0.077)^2) / 8896
#### ME = 0.0211

#### Since the correlation coefficient is negative, we know there is a negative relationship between the two variables. Since the margin of error is less than the correlation in magnitude, we know that the correlation is significant.

### b) Compute the α, the cross-product ratio.
#### α = ad / bc
#### α = (3658 * 863) / (2715 * 1660)
#### α = 0.7

### c) Compute the Q, Yule’s Q.
#### Q = (α - 1) / (α + 1)
#### Q = (0.7 - 1) / (0.7 + 1)
#### Q = −0.176

### 5. In the quadratic regression model, Y = β0 + β1X + β2X2, when β2 is NOT significantly different from 0, we can conclude that...

#### B. There is no quadratic relationship between X and Y



### 6. If coefficient of determination of a simple linear regression model is 97.5%, what is the value of the correlation (in magnitude) between the predictor and target variables?

#### R^2 = r^2
#### r = +/- sqrt(R^2)
#### r = +/- 0.987

#### The correlation coefficient confirms a strong linear relationship between the two variables in the simple linear regression model.

### 7. Why is the the natural-log transformation popular in model building?

#### The natural-log transformation is popular in model building when faced with right-skewed data. Taking the natural log of the right-skewed data transforms the data to follow a more normal distribution. It effectively reduces the skewness of the data.

### 8. Which of the following is the best way to determine whether or not there is statistically significant linear relationship between two numeric variables?

#### C. Compare the estimated slope and its margin of error.

### 9. What are the steps that a data scientist needs to follow to include categorical variables such as NBA position in a linear regression model, in which points scored per game is the target variable? 

#### To include categorical variables in a linear regression model, we need to convert the categorical variable into a quantitative variable by using an indicator/dummy variable. A categorical variable that takes on one of two values can typically be simplified as a quantitative variable with values of 0 and 1. For categorical variables that take on m values where m > 2, we can create m - 1 new variables that take on the values of 0 and 1. Example: NHL positions center, defense, goalie. We create two new variables, Z1 and Z2. When center -> Z1 = 1, Z2 = 0. When defense -> Z1 = 0, Z2 = 1. When goalie -> Z1 = 0, Z2 = 0. This way, each possible value is accounted for.

### 10. In multiple linear regression, the least squares regression line minimizes the sum of the...

#### D. Squared differences between actual and predicted Y values.

### 11. Considering the following multiple regression model: Y = 8.84 + 3.23X − 7.11PC − 2.71PF where Y represents points scored in 2011-2012 NBA season, X denote the player’s offensive rebounds per game for that season, PC denotes the indicator variable for centers, and PF denotes the indicator variable for forwards. The predictor variable X is found to be highly significant, then we would conclude that ...?

#### Since the predictor variable X is found to be highly significant, we can conclude that changes in a player's offensive rebounds per game (X) produce a significant change in the points scored by that player (Y). Specifically, for one unit increase in X, holding PC and PF constant, on average, Y increases by 3.23.

In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

## 12. a) Considering the Hitters data set.  Using pandas to read the csv file and create a data-frame called hitters
## and removing observations with missing values
hitters = pd.read_csv('Hitters.csv')
hitters = hitters.dropna()

hitters.head()

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
1,315,81,7,24,38,39,14,3449,835,69,321,414,375,N,W,632,43,10,475.0,N
2,479,130,18,66,72,76,3,1624,457,63,224,266,263,A,W,880,82,14,480.0,A
3,496,141,20,65,78,37,11,5628,1575,225,828,838,354,N,E,200,11,3,500.0,N
4,321,87,10,39,42,30,2,396,101,12,48,46,33,N,E,805,40,4,91.5,N
5,594,169,4,74,51,35,11,4408,1133,19,501,336,194,A,W,282,421,25,750.0,A

In [2]:
## b) Creating the following variables:

## log_Salary that represents the log of Salary 
## League_0_1 that takes the value of 1 when League = A and 0 otherwise

hitters['log_Salary'] = np.log(hitters['Salary'])
hitters['League_0_1'] = np.where(hitters['League'] == 'A', 1, 0)

hitters.head()

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,...,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague,log_Salary,League_0_1
1,315,81,7,24,38,39,14,3449,835,69,...,375,N,W,632,43,10,475.0,N,6.163315,0
2,479,130,18,66,72,76,3,1624,457,63,...,263,A,W,880,82,14,480.0,A,6.173786,1
3,496,141,20,65,78,37,11,5628,1575,225,...,354,N,E,200,11,3,500.0,N,6.214608,0
4,321,87,10,39,42,30,2,396,101,12,...,33,N,E,805,40,4,91.5,N,4.516339,0
5,594,169,4,74,51,35,11,4408,1133,19,...,194,A,W,282,421,25,750.0,A,6.620073,1

In [3]:
## c) Building a linear regression model in which AtBat, Hits, HmRun, and League_0_1 are the predictor 
## variables and log_Salary is the target variable

## Building the model
lm_md = smf.ols(formula = 'log_Salary ~ AtBat + Hits + HmRun + League_0_1', data = hitters).fit()

## Extracting model results
lm_md.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             log_Salary   R-squared:                       0.233
Model:                            OLS   Adj. R-squared:                  0.221
Method:                 Least Squares   F-statistic:                     19.56
Date:                Mon, 22 Nov 2021   Prob (F-statistic):           4.51e-14
Time:                        10:55:27   Log-Likelihood:                -306.97
No. Observations:                 263   AIC:                             623.9
Df Residuals:                     258   BIC:                             641.8
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.1585      0.153     33.671      0.000       4.857       5.460
AtBat         -0.0022      0.001     -1.748      0.082      -0.005       0.000
Hits           0.0142      0.004      3.508      0.001       0.006       0.022
HmRun          0.0183      0.007      2.714      0.007       0.005       0.032
League_0_1    -0.1570      0.100     -1.577      0.116      -0.353       0.039
==============================================================================
Omnibus:                        4.364   Durbin-Watson:                   1.880
Prob(Omnibus):                  0.113   Jarque-Bera (JB):                3.997
Skew:                          -0.236   Prob(JB):                        0.136
Kurtosis:                       2.622   Cond. No.                     1.43e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.43e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [4]:
## Using the multiple linear regression model to answer the following:

## i) Reporting the coefficient of determination

## The coefficient of determination (R-squared) value for this model is 0.233.
## In the context of this problem, we can say that 23.3% of the variability in log Salary can be explained 
## by a linear model in which AtBat, Hits, HmRun, and League_0_1 are the predictor variables.

In [5]:
## ii) Describing the relationship between log_Salary and AtBat

## Atbat has an estimated coefficient of -0.0022 with an associated standard error of 0.001. Since the estimated coefficient 
## is negative, we know that there is a negative relationship between the two variables. Also, since the estimated coefficient 
## is greater than the margin of error (2 * std. error) in magnitude, we conclude this relationship is significant.

In [6]:
## iii) Describing the relationship between log_Salary and League_0_1 

## League_0_1 has an estimated coefficient of -0.1570 with an associated standard error of 0.1. Since the estimated coefficient 
## is negative, we know that there is a negative relationship between the two variables. Also, since the estimated coefficient 
## is less than the margin of error (2 * std. error) in magnitude, we conclude this relationship is not significant.

In [4]:
## iv) Predicting the salary of a baseball player in the 1987 season with AtBat = 650, Hits = 250, 
## HmRun = 37 and League_0_1 = 0

## Defining the new data
new_data = pd.DataFrame({'AtBat':[650], 'Hits': [250], 'HmRun': [37], 'League_0_1': [0]})

## Predicting log_Salary
log_salary = lm_md.predict(new_data)

## Predicting the Salary
np.exp(log_salary)

## The estimated salary for a player in 1987 with AtBat = 650, Hits = 250, HmRun = 37 and League_0_1 = 0 is
## approximately $2,829,637.

0    2829.636606
dtype: float64

In [5]:
## v) Predicting the salary of a baseball player in the 1987 season with AtBat = 650, Hits = 250, 
## HmRun = 37 and League_0_1 = 1

## Defining the new data
new_data = pd.DataFrame({'AtBat':[650], 'Hits': [250], 'HmRun': [37], 'League_0_1': [1]})

## Predicting log_Salary
log_salary = lm_md.predict(new_data)

## Predicting the Salary
np.exp(log_salary)

## The estimated salary for a player in 1987 with AtBat = 650, Hits = 250, HmRun = 37 and League_0_1 = 1 is
## approximately $2,418,472.

0    2418.471522
dtype: float64

In [ ]:
## vi) When comparing the salary between players with similar statistics in the American League versus the 
## National League, we can conclude that players from the National League (League_0_1 = 0) have a higher salary, 
## on average, compared to a player from the American League (League_0_1 = 1).

In [6]:
## vii) Calculating the Standardized Regression Coefficients

std_log_Salary = hitters['log_Salary'].std()
std_AtBat = hitters['AtBat'].std()
std_Hits = hitters['Hits'].std()
std_HmRun = hitters['HmRun'].std()
std_league_0_1 = hitters['League_0_1'].std()

print('Standardized Coefficient of AtBat:', 0.0022 * std_AtBat / std_log_Salary)
print('Standardized Coefficient of Hits:', 0.0142 * std_Hits / std_log_Salary)
print('Standardized Coefficient of HmRun:', 0.0183 * std_HmRun / std_log_Salary)
print('Standardized Coefficient of League_0_1:', 0.157 * std_league_0_1 / std_log_Salary)

## In terms of the standardized regression coefficient, Hits is the most important variable (highest standardized 
## regression coefficient) and League_0_1 is the least important variable (lowest standardized regression coefficient).

Standardized Coefficient of AtBat: 0.3644609012608325
Standardized Coefficient of Hits: 0.7206310315583603
Standardized Coefficient of HmRun: 0.18022541981157092
Standardized Coefficient of League_0_1: 0.08830669658408402

In [7]:
## vii) Calculating the Contribution to R-squared values

corr_ls_AtBat = hitters[['log_Salary', 'AtBat']].corr().iloc[0, 1]
corr_ls_Hits = hitters[['log_Salary', 'Hits']].corr().iloc[0, 1]
corr_ls_HmRun = hitters[['log_Salary', 'HmRun']].corr().iloc[0, 1]
corr_ls_League_0_1 = hitters[['log_Salary', 'League_0_1']].corr().iloc[0, 1]


print('The contribution of AtBat to R^2 is', round(100 * 0.0022 * std_AtBat * corr_ls_AtBat / std_log_Salary, 2))
print('The contribution of Hits to R^2 is', round(100 * 0.0142 * std_Hits * corr_ls_Hits / std_log_Salary, 2))
print('The contribution of HmRun to R^2 is', round(100 * 0.0183 * std_HmRun * corr_ls_HmRun / std_log_Salary, 2))
print('The contribution of League_0_1 to R^2 is', round(100 * 0.157 * std_league_0_1 * corr_ls_League_0_1 / std_log_Salary, 2))

## In terms of the contribution of the variable to R2, Hits is the most important variable (highest contribution to R^2) 
## and League_0_1 is the least important variable (lowest contribution to R^2).

The contribution of AtBat to R^2 is 15.12
The contribution of Hits to R^2 is 32.4
The contribution of HmRun to R^2 is 6.13
The contribution of League_0_1 to R^2 is 0.06